// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AIService proxies chat requests to OpenAI API with DB context injection
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearChatHistory deletes all chat messages for a connection
 */
export function ClearChatHistory(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(724967167, connectionID);
}

/**
 * GetChatHistory returns persisted chat messages for a connection
 */
export function GetChatHistory(connectionID: string): $CancellablePromise<store$0.ChatMessage[]> {
    return $Call.ByID(4162074904, connectionID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSelectedModel returns the persisted model selection for a connection
 */
export function GetSelectedModel(connectionID: string): $CancellablePromise<string> {
    return $Call.ByID(2371173956, connectionID);
}

/**
 * ListModels returns the available AI models
 */
export function ListModels(): $CancellablePromise<$models.ModelInfo[]> {
    return $Call.ByID(324690072).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SendMessage sends a chat message and streams the response via events
 */
export function SendMessage(connectionID: string, message: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(3818713495, connectionID, message, model);
}

/**
 * SetApp sets the Wails application reference
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2164955777, app);
}

/**
 * SetSelectedModel persists the model selection for a connection
 */
export function SetSelectedModel(connectionID: string, modelID: string): $CancellablePromise<void> {
    return $Call.ByID(3997526600, connectionID, modelID);
}

/**
 * StopStreaming cancels an ongoing AI response stream
 */
export function StopStreaming(connectionID: string): $CancellablePromise<void> {
    return $Call.ByID(1573700206, connectionID);
}

// Private type creation functions
const $$createType0 = store$0.ChatMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ModelInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
