// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService manages database connections (bound to Wails frontend)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as driver$0 from "../internal/driver/models.js";

/**
 * Connect establishes a live connection to a saved database
 */
export function Connect(id: string): $CancellablePromise<void> {
    return $Call.ByID(2358662722, id);
}

/**
 * DeleteConnection removes a connection (disconnects first if active)
 */
export function DeleteConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(1931888415, id);
}

/**
 * Disconnect closes an active connection
 */
export function Disconnect(id: string): $CancellablePromise<void> {
    return $Call.ByID(2202414982, id);
}

/**
 * GetDriver returns the active driver for a connection (internal use)
 */
export function GetDriver(id: string): $CancellablePromise<driver$0.Driver> {
    return $Call.ByID(116988934, id);
}

/**
 * ListConnections returns all saved connections with current status
 */
export function ListConnections(): $CancellablePromise<driver$0.ConnectionConfig[]> {
    return $Call.ByID(194740469).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveConnection creates or updates a connection config
 */
export function SaveConnection(cfg: driver$0.ConnectionConfig): $CancellablePromise<driver$0.ConnectionConfig> {
    return $Call.ByID(3004936485, cfg).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * TestConnection attempts to connect and immediately disconnects
 */
export function TestConnection(cfg: driver$0.ConnectionConfig): $CancellablePromise<void> {
    return $Call.ByID(2082205888, cfg);
}

// Private type creation functions
const $$createType0 = driver$0.ConnectionConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
