// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EditService handles inline cell editing (bound to Wails frontend)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BatchUpdateCells applies multiple cell edits, stopping on first error
 */
export function BatchUpdateCells(connectionID: string, reqs: $models.CellUpdateRequest[]): $CancellablePromise<$models.BatchUpdateResult | null> {
    return $Call.ByID(1247905070, connectionID, reqs).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteRows deletes one or more rows by their primary key values
 */
export function DeleteRows(connectionID: string, table: string, pkValuesList: { [_ in string]?: any }[]): $CancellablePromise<$models.DeleteResult | null> {
    return $Call.ByID(2251769390, connectionID, table, pkValuesList).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTablePrimaryKey returns the primary key column names for a table
 */
export function GetTablePrimaryKey(connectionID: string, table: string): $CancellablePromise<string[]> {
    return $Call.ByID(3677196349, connectionID, table).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * InsertRow inserts a new row into the given table
 */
export function InsertRow(connectionID: string, table: string, values: { [_ in string]?: any }): $CancellablePromise<$models.InsertResult | null> {
    return $Call.ByID(2939170931, connectionID, table, values).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * UpdateCell executes an UPDATE for a single cell and returns the SQL + result
 */
export function UpdateCell(connectionID: string, req: $models.CellUpdateRequest): $CancellablePromise<$models.CellUpdateResult | null> {
    return $Call.ByID(4026412721, connectionID, req).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = $models.BatchUpdateResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DeleteResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $models.InsertResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.CellUpdateResult.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
