// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings holds all user-configurable settings
 */
export class AppSettings {
    /**
     * General
     */
    "autoConnect": boolean;
    "confirmDangerous": boolean;
    "maxHistory": number;

    /**
     * Appearance
     */
    "theme": string;
    "fontSize": number;
    "rowDensity": string;

    /**
     * Editor
     */
    "tabSize": number;
    "wordWrap": boolean;
    "lineNumbers": boolean;
    "autoUppercase": boolean;

    /**
     * Query Execution
     */
    "queryTimeout": number;
    "defaultLimit": number;
    "confirmMutations": boolean;
    "autoLimit": boolean;

    /**
     * Connection
     */
    "connectionTimeout": number;

    /**
     * Data & Export
     */
    "nullDisplay": string;
    "dateFormat": string;
    "exportFormat": string;
    "csvDelimiter": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("autoConnect" in $$source)) {
            this["autoConnect"] = false;
        }
        if (!("confirmDangerous" in $$source)) {
            this["confirmDangerous"] = false;
        }
        if (!("maxHistory" in $$source)) {
            this["maxHistory"] = 0;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("rowDensity" in $$source)) {
            this["rowDensity"] = "";
        }
        if (!("tabSize" in $$source)) {
            this["tabSize"] = 0;
        }
        if (!("wordWrap" in $$source)) {
            this["wordWrap"] = false;
        }
        if (!("lineNumbers" in $$source)) {
            this["lineNumbers"] = false;
        }
        if (!("autoUppercase" in $$source)) {
            this["autoUppercase"] = false;
        }
        if (!("queryTimeout" in $$source)) {
            this["queryTimeout"] = 0;
        }
        if (!("defaultLimit" in $$source)) {
            this["defaultLimit"] = 0;
        }
        if (!("confirmMutations" in $$source)) {
            this["confirmMutations"] = false;
        }
        if (!("autoLimit" in $$source)) {
            this["autoLimit"] = false;
        }
        if (!("connectionTimeout" in $$source)) {
            this["connectionTimeout"] = 0;
        }
        if (!("nullDisplay" in $$source)) {
            this["nullDisplay"] = "";
        }
        if (!("dateFormat" in $$source)) {
            this["dateFormat"] = "";
        }
        if (!("exportFormat" in $$source)) {
            this["exportFormat"] = "";
        }
        if (!("csvDelimiter" in $$source)) {
            this["csvDelimiter"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * AuthStatus represents the current authentication state
 */
export class AuthStatus {
    /**
     * "logged_in", "logged_out", "expired"
     */
    "status": string;
    "email"?: string;

    /** Creates a new AuthStatus instance. */
    constructor($$source: Partial<AuthStatus> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthStatus($$parsedSource as Partial<AuthStatus>);
    }
}

/**
 * BatchUpdateResult holds results for multiple cell updates
 */
export class BatchUpdateResult {
    "results": CellUpdateResult[];
    "totalSuccess": number;
    "totalFailed": number;

    /** Creates a new BatchUpdateResult instance. */
    constructor($$source: Partial<BatchUpdateResult> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }
        if (!("totalSuccess" in $$source)) {
            this["totalSuccess"] = 0;
        }
        if (!("totalFailed" in $$source)) {
            this["totalFailed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BatchUpdateResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new BatchUpdateResult($$parsedSource as Partial<BatchUpdateResult>);
    }
}

/**
 * CellUpdateRequest describes a single cell update
 */
export class CellUpdateRequest {
    "table": string;

    /**
     * e.g. {"id": 5} or {"a": 1, "b": 2}
     */
    "pkColumns": { [_ in string]?: any };
    "column": string;

    /**
     * nil = SET NULL
     */
    "newValue": any;

    /** Creates a new CellUpdateRequest instance. */
    constructor($$source: Partial<CellUpdateRequest> = {}) {
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("pkColumns" in $$source)) {
            this["pkColumns"] = {};
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("newValue" in $$source)) {
            this["newValue"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CellUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CellUpdateRequest {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pkColumns" in $$parsedSource) {
            $$parsedSource["pkColumns"] = $$createField1_0($$parsedSource["pkColumns"]);
        }
        return new CellUpdateRequest($$parsedSource as Partial<CellUpdateRequest>);
    }
}

/**
 * CellUpdateResult holds the result of a single cell update
 */
export class CellUpdateResult {
    "generatedSQL": string;
    "success": boolean;
    "error"?: string;

    /** Creates a new CellUpdateResult instance. */
    constructor($$source: Partial<CellUpdateResult> = {}) {
        if (!("generatedSQL" in $$source)) {
            this["generatedSQL"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CellUpdateResult instance from a string or object.
     */
    static createFrom($$source: any = {}): CellUpdateResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CellUpdateResult($$parsedSource as Partial<CellUpdateResult>);
    }
}

/**
 * DeleteResult holds the result of a delete operation
 */
export class DeleteResult {
    "generatedSQL": string[];
    "totalDeleted": number;
    "success": boolean;
    "error"?: string;

    /** Creates a new DeleteResult instance. */
    constructor($$source: Partial<DeleteResult> = {}) {
        if (!("generatedSQL" in $$source)) {
            this["generatedSQL"] = [];
        }
        if (!("totalDeleted" in $$source)) {
            this["totalDeleted"] = 0;
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeleteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): DeleteResult {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("generatedSQL" in $$parsedSource) {
            $$parsedSource["generatedSQL"] = $$createField0_0($$parsedSource["generatedSQL"]);
        }
        return new DeleteResult($$parsedSource as Partial<DeleteResult>);
    }
}

/**
 * InsertResult holds the result of an insert operation
 */
export class InsertResult {
    "generatedSQL": string;
    "success": boolean;
    "error"?: string;

    /** Creates a new InsertResult instance. */
    constructor($$source: Partial<InsertResult> = {}) {
        if (!("generatedSQL" in $$source)) {
            this["generatedSQL"] = "";
        }
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InsertResult instance from a string or object.
     */
    static createFrom($$source: any = {}): InsertResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InsertResult($$parsedSource as Partial<InsertResult>);
    }
}

/**
 * ModelInfo describes an available AI model
 */
export class ModelInfo {
    "id": string;
    "name": string;
    "category": string;
    "description": string;

    /** Creates a new ModelInfo instance. */
    constructor($$source: Partial<ModelInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            this["category"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelInfo($$parsedSource as Partial<ModelInfo>);
    }
}

// Private type creation functions
const $$createType0 = CellUpdateResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
