// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OAuthService manages OAuth 2.0 PKCE flow for ChatGPT authentication
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetAuthStatus returns the current authentication state
 */
export function GetAuthStatus(): $CancellablePromise<$models.AuthStatus> {
    return $Call.ByID(2549554919).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetValidToken returns a valid access token, refreshing if needed
 */
export function GetValidToken(clientID: string): $CancellablePromise<string> {
    return $Call.ByID(1698481044, clientID);
}

/**
 * Logout clears stored tokens
 */
export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(4220511911);
}

/**
 * SetApp sets the Wails application reference (called after app creation)
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4092327922, app);
}

/**
 * StartOAuthLogin initiates the OAuth PKCE flow
 */
export function StartOAuthLogin(clientID: string): $CancellablePromise<void> {
    return $Call.ByID(3636768903, clientID);
}

// Private type creation functions
const $$createType0 = $models.AuthStatus.createFrom;
