// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryService handles query execution (bound to Wails frontend)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as driver$0 from "../internal/driver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../internal/store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSnippet removes a snippet
 */
export function DeleteSnippet(id: number): $CancellablePromise<void> {
    return $Call.ByID(945714082, id);
}

/**
 * ExecutePaginatedQuery runs a paginated SELECT * on a table and returns data + total count
 */
export function ExecutePaginatedQuery(connectionID: string, table: string, page: number, pageSize: number): $CancellablePromise<$models.PaginatedResult | null> {
    return $Call.ByID(681887436, connectionID, table, page, pageSize).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ExecuteQuery runs a query on the given connection and records history
 */
export function ExecuteQuery(connectionID: string, query: string): $CancellablePromise<driver$0.QueryResult | null> {
    return $Call.ByID(2155422459, connectionID, query).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetHistory returns query history for a connection
 */
export function GetHistory(connectionID: string, limit: number): $CancellablePromise<store$0.HistoryEntry[]> {
    return $Call.ByID(1597289098, connectionID, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListSnippets returns saved snippets
 */
export function ListSnippets(connectionID: string): $CancellablePromise<store$0.Snippet[]> {
    return $Call.ByID(854831104, connectionID).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SaveSnippet saves a query snippet
 */
export function SaveSnippet(snippet: store$0.Snippet): $CancellablePromise<void> {
    return $Call.ByID(2254103504, snippet);
}

// Private type creation functions
const $$createType0 = $models.PaginatedResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = driver$0.QueryResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = store$0.HistoryEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = store$0.Snippet.createFrom;
const $$createType7 = $Create.Array($$createType6);
