// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchemaService handles schema introspection and DDL (bound to Wails frontend)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as driver$0 from "../internal/driver/models.js";

/**
 * GetColumns returns columns for a table
 */
export function GetColumns(connectionID: string, table: string): $CancellablePromise<driver$0.ColumnInfo[]> {
    return $Call.ByID(1236608136, connectionID, table).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetFunctions returns functions for a connection
 */
export function GetFunctions(connectionID: string): $CancellablePromise<driver$0.FunctionInfo[]> {
    return $Call.ByID(2253813954, connectionID).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTables returns all tables for a connection
 */
export function GetTables(connectionID: string): $CancellablePromise<driver$0.TableInfo[]> {
    return $Call.ByID(2427864504, connectionID).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetViews returns views for a connection
 */
export function GetViews(connectionID: string): $CancellablePromise<string[]> {
    return $Call.ByID(2837470909, connectionID).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = driver$0.ColumnInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = driver$0.FunctionInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = driver$0.TableInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
