// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService manages app settings (bound to Wails frontend)
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConnectionTimeout returns the current connection timeout in seconds (for internal use)
 */
export function GetConnectionTimeout(): $CancellablePromise<number> {
    return $Call.ByID(1161361698);
}

/**
 * GetQueryTimeout returns the current query timeout in seconds (for internal use)
 */
export function GetQueryTimeout(): $CancellablePromise<number> {
    return $Call.ByID(2333792672);
}

/**
 * GetSettings returns current settings (defaults merged with user overrides)
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2070228810).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateSettings saves settings and invalidates cache
 */
export function UpdateSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1924741913, settings);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
