// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class HistoryEntry {
    "id": number;
    "connectionId": string;
    "queryText": string;

    /**
     * success, error, mutation
     */
    "status": string;
    "executionTime": number;
    "rowsAffected": number;
    "errorMessage"?: string;
    "createdAt": string;

    /** Creates a new HistoryEntry instance. */
    constructor($$source: Partial<HistoryEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("queryText" in $$source)) {
            this["queryText"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("executionTime" in $$source)) {
            this["executionTime"] = 0;
        }
        if (!("rowsAffected" in $$source)) {
            this["rowsAffected"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): HistoryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryEntry($$parsedSource as Partial<HistoryEntry>);
    }
}

export class Snippet {
    "id": number;
    "connectionId": string;
    "title": string;
    "queryText": string;
    "tags": string[];
    "createdAt": string;

    /** Creates a new Snippet instance. */
    constructor($$source: Partial<Snippet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("connectionId" in $$source)) {
            this["connectionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("queryText" in $$source)) {
            this["queryText"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     */
    static createFrom($$source: any = {}): Snippet {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new Snippet($$parsedSource as Partial<Snippet>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
