// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ColumnInfo describes a table column's schema
 */
export class ColumnInfo {
    "name": string;
    "type": string;
    "nullable": boolean;
    "primaryKey": boolean;
    "unique": boolean;
    "defaultValue"?: string;
    "extra"?: string;
    "ordinalPos": number;

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("primaryKey" in $$source)) {
            this["primaryKey"] = false;
        }
        if (!("unique" in $$source)) {
            this["unique"] = false;
        }
        if (!("ordinalPos" in $$source)) {
            this["ordinalPos"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

/**
 * ColumnMeta describes a result column
 */
export class ColumnMeta {
    "name": string;
    "type": string;

    /** Creates a new ColumnMeta instance. */
    constructor($$source: Partial<ColumnMeta> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnMeta($$parsedSource as Partial<ColumnMeta>);
    }
}

/**
 * ConnectionConfig holds connection parameters
 */
export class ConnectionConfig {
    "id": string;
    "name": string;
    "type": DatabaseType;
    "host": string;
    "port": number;
    "database": string;
    "username": string;
    "password": string;

    /**
     * For SQLite
     */
    "filePath"?: string;
    "sslMode"?: string;

    /**
     * connected, idle, offline
     */
    "status": string;
    "lastUsed"?: string;

    /** Creates a new ConnectionConfig instance. */
    constructor($$source: Partial<ConnectionConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = DatabaseType.$zero;
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectionConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionConfig($$parsedSource as Partial<ConnectionConfig>);
    }
}

/**
 * DatabaseType represents supported database types
 */
export enum DatabaseType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MySQL = "mysql",
    MariaDB = "mariadb",
    PostgreSQL = "postgresql",
    SQLite = "sqlite",
    MongoDB = "mongodb",
    Redshift = "redshift",
};

/**
 * Driver is the unified interface all database adapters implement
 */
export type Driver = any;

/**
 * FunctionInfo describes a stored function/procedure
 */
export class FunctionInfo {
    "name": string;

    /**
     * function, procedure
     */
    "type": string;

    /** Creates a new FunctionInfo instance. */
    constructor($$source: Partial<FunctionInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FunctionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): FunctionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FunctionInfo($$parsedSource as Partial<FunctionInfo>);
    }
}

/**
 * QueryResult is returned from query execution
 */
export class QueryResult {
    "columns": ColumnMeta[];
    "rows": { [_ in string]?: any }[];
    "rowCount": number;
    "affectedRows": number;

    /**
     * milliseconds
     */
    "executionTime": number;
    "error"?: string;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowCount" in $$source)) {
            this["rowCount"] = 0;
        }
        if (!("affectedRows" in $$source)) {
            this["affectedRows"] = 0;
        }
        if (!("executionTime" in $$source)) {
            this["executionTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

/**
 * TableInfo describes a table or view
 */
export class TableInfo {
    "name": string;

    /**
     * table, view
     */
    "type": string;
    "schema"?: string;
    "rowCount"?: number;

    /** Creates a new TableInfo instance. */
    constructor($$source: Partial<TableInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TableInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableInfo($$parsedSource as Partial<TableInfo>);
    }
}

// Private type creation functions
const $$createType0 = ColumnMeta.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($$createType2);
