/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExplorerConnectionIdRouteImport } from './routes/explorer/$connectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerConnectionIdRoute = ExplorerConnectionIdRouteImport.update({
  id: '/explorer/$connectionId',
  path: '/explorer/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explorer/$connectionId': typeof ExplorerConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer/$connectionId': typeof ExplorerConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explorer/$connectionId': typeof ExplorerConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/explorer/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/explorer/$connectionId'
  id: '__root__' | '/' | '/explorer/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExplorerConnectionIdRoute: typeof ExplorerConnectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/$connectionId': {
      id: '/explorer/$connectionId'
      path: '/explorer/$connectionId'
      fullPath: '/explorer/$connectionId'
      preLoaderRoute: typeof ExplorerConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExplorerConnectionIdRoute: ExplorerConnectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
